### ISSUE TITLE
dataset organization questions，cannot solve

### ISSUE THREAD

**Issue by xiaoxiaoxiaofufu** [kdwonn/DivE#1]
I download data from this link，https://github.com/kuanghuei/SCAN#download-data，and organise as your suggestions，there is something wrong..

could you show me your organisation of datasets and the whole procedure as well ?what and where  is the id_mapping.json?

my organisation is as follows
![image](https://github.com/kdwonn/DivE/assets/136477677/42f07fa4-b3c4-47bc-b6df-fe72d3d8d225)
![image](https://github.com/kdwonn/DivE/assets/136477677/11d5cf71-32ca-4aff-86a4-b9871e96b9fe)

**Comment by kdwonn** [comment]
Hello, thank you for your interest.

vocab `.json` files require additional post-processing by saving it as a `.pkl` file.

I think `python vocab.py --from_json ./vocab/coco_precomp_vocab.json` will fix the issue.
