### ISSUE TITLE
Purpose of "recovery" in train? and "txt_len"?

### ISSUE THREAD

**Issue by JayC1208** [kdwonn/DivE#5]
Hi, I am trying to understand the code and have a question about recovery and txt_len.

So "recovery" is applied only for the text embeddings, and I don't get the purpose of this.
When I checked the data.py, the recovery was identical to img_id. 
I think applying recovery is unnecessary cause the answer sentences are paired with images in the sampling process of the dataloader.

Also, for the txt_len variable, it is just "index" in data.py and it is suddenly used as a txt_len, and even delivered to the tokenizer.

can you provide some explanation for this to help me understand?

**Comment by kdwonn** [comment]
Hey there! Thanks for checking out our work.

I get it might look a bit confusing at first, but the outputs from the __get_item__ of the dataloader are processed into batches through custom [collate functions](https://discuss.pytorch.org/t/how-to-create-a-dataloader-with-variable-size-input/8278). Take a peek [here](https://github.com/kdwonn/DivE/blob/8ebb9a802ec160a9d4e4bf7c552feff56a3de4e5/data.py#L879).
