### ISSUE TITLE
how can I get the dataset_flickr30k.json ?

### ISSUE THREAD

**Issue by xiaoxiaoxiaofufu** [kdwonn/DivE#6]
I follow the f30k link you provide, it seems that there is not an off the shelf json file.
![image](https://github.com/kdwonn/DivE/assets/136477677/53cd9c0e-f668-4c6c-a33b-9a3e9e52766d)

**Comment by kdwonn** [comment]
Hello!

You can find the .json file containing captions in [here](https://cs.stanford.edu/people/karpathy/deepimagesent/).
