### ISSUE TITLE
Figure 2.(b) Details of our attention maps that slots of each iteration produce.

### ISSUE THREAD

**Issue by 2950906781** [kdwonn/DivE#8]
The diagram you made to visualize the weights is very good, how did you make it, and is there any code for it?

**Comment by kdwonn** [comment]
I used the hook functionality of PyTorch to obtain attention map during forward. It is the very messy scripts written on the fly during submission, so I don't have a plan to include it in this repo. However, using hook to visualize attention map is very convenient, and you can find many materials describing how you can do it (https://blog.paperspace.com/pytorch-hooks-gradient-clipping-debugging/).
